### ISSUE TITLE
Piping output of curl to bash without using an SSL

### ISSUE THREAD

**Issue by iMerica** [sleekbyte/tailor#213]
RE: install steps in your README:

    Requires Java (JRE or JDK) Version 8 or above: Java SE Downloads

    Mac OS X (10.10+), Linux (Ubuntu, etc.)

    curl -fsSL http://tailor.sh/install.sh | sh

Until tailor.sh is protected by an SSL, would it not be more secure for users to keep the script in a Github release or use HomeBrew instead?

**Comment by RohanNagar** [comment]
Would love to have this available via Homebrew. I just installed via curl and love Tailor, but for my build machines I'll need to install via Homebrew, so I can't integrate this into my workflow quite yet. Thanks for the awesome tool!

**Comment by alykhank** [comment]
@iMerica yes, that's a great suggestion! As of right now, a working alternative is to use the GitHub hosted endpoint:
```bash
curl -fsSL https://raw.githubusercontent.com/sleekbyte/tailor/master/script/install.sh | sh
```

* We are also attempting to get SSL enabled on our domain so we can still use the pretty URL :smile:
* Homebrew distribution is in the works, and thanks for the feedback @RohanNagar!

**Comment by alykhank** [comment]
We have switched all website links to HTTPS, and also support Homebrew installation now!
Documentation is updated as well, thanks again to both of you for your feedback.

**Comment by RohanNagar** [comment]
Thanks again! I have already integrated Tailor into my build and it works great!
