### ISSUE TITLE
Disabled Errors Still Return Nonzero

### ISSUE THREAD

**Issue by bbqbaron** [sleekbyte/tailor#226]
It's my understanding that the comment `// tailor:disable` is intended to prevent Tailor from validating a line. However, it appears that a disabled error will still cause the `tailor` command to return nonzero if `--max-severity=error`. This doesn't seem like the intended behavior; maybe I misunderstand what it's for?

As it is, we cannot fail XCode builds for any error, since we have errors in our code for which we have disabled Tailor.

**Comment by adityatrivedi** [comment]
@bbqbaron thanks for reporting the issue!  It was a bug and has been fixed in #227.  The bug fix will be incorporated in the next release.

**Comment by bbqbaron** [comment]
My pleasure; thanks for the quick fix!
