### ISSUE TITLE
Apply formatting to source files

### ISSUE THREAD

**Issue by nburns** [sleekbyte/tailor#270]
I can't tell from the built-in help, but it looks like it is not possible to have Tailor reformat my source files.

Are there any plans to add reformatting support like clang-format and gofmt?

**Comment by alykhank** [comment]
Currently, Tailor does not have this capability but it is being considered. We would like to know how developers would prefer to have this implemented, i.e.:

1. acting directly upon files on the filesystem (assuming you have appropriate version control backups)
2. output/display a suggested diff on the console or to a file that could be applied (e.g. using Git)
3. use an Xcode plugin to control individual reformatting on a case-by-case basis

**Comment by adityatrivedi** [comment]
Moving the discussion to #375.
