### ISSUE TITLE
Relax lower-camel-case rule for operator functions

### ISSUE THREAD

**Issue by mattwest** [sleekbyte/tailor#271]
Currently, if a function name contains symbols with no letters (such as `==`), Tailor incorrectly reports a lower-camel-case rule violation.

Please would you consider changing lower-camel-case to _not_ act on operator functions?

```
public struct Position {
    let row: Int
    let column: Int
}

extension Position: Equatable {}

public func ==(lhs: Position, rhs: Position) -> Bool {
    return (lhs.row == rhs.row)
        && (lhs.column == rhs.column)
}
```

**Comment by adityatrivedi** [comment]
@mattwest thanks for reporting the issue! It was a bug and has been fixed in #273. The bug fix will be incorporated in the next release.
