### ISSUE TITLE
Need exception-rule for handling of equatable protocol

### ISSUE THREAD

**Issue by ArtSabintsev** [sleekbyte/tailor#286]
For a class to conform to the [Equatable](https://developer.apple.com/library/ios/documentation/Swift/Reference/Swift_Equatable_Protocol/) protocol, it must define a function of the of the following form:

```
func ==(lhs: Class, rhs: Class) -> Bool
```

Unfortunately, Tailor throws a warning here: 
**[lower-camel-case] Function names should be lowerCamelCase**

I know I can add some inline code to silence this warning, but I think Tailor should treat this as an exception to the lower-camel-case rule.

**Comment by alykhank** [comment]
Thanks for reporting @ArtSabintsev! This was actually fixed in yesterday's release, v0.4.0, and tracked in #271. Please update and let us know if you're still experiencing the issue.

**Comment by ArtSabintsev** [comment]
Will do!

**Comment by ArtSabintsev** [comment]
Confirmed fixed - thanks!

**Comment by alykhank** [comment]
No problem, happy to help :)
