### ISSUE TITLE
Xcode Bots Issue

### ISSUE THREAD

**Issue by ArtSabintsev** [sleekbyte/tailor#296]
I'm having an issue with Tailor when running my project through Xcode Bots. See attached screenshot.

<img width="410" alt="screen shot 2016-01-13 at 12 06 51 am" src="https://cloud.githubusercontent.com/assets/854860/12286444/afdbd556-b989-11e5-9752-6043a0731f62.png">

The script runs fine during the build phase, but during the analyze phase, the bot can't seem too find the script. Any idea what to do about this issue? Do I need a pre-integration trigger? If so, do you know what it should look like?

**Comment by alykhank** [comment]
I believe the Analyze phase may have a different `$PATH` setting that does not include `/usr/local/bin`, so you could try either specifying the full path `/usr/local/bin/tailor` when invoking the script, or modifying the `$PATH` within the phase script:
```bash
export PATH="$PATH:/usr/local/bin"
```

**Comment by ArtSabintsev** [comment]
That worked perfectly! Thanks!
