### ISSUE TITLE
Linting Storyboards

### ISSUE THREAD

**Issue by ArtSabintsev** [sleekbyte/tailor#302]
Specifically a rule for `misplaced="YES"`. If it exists, throw an error.

Thoughts?

**Comment by ArtSabintsev** [comment]
On second thought, this is XML, not Swift, so I'm not sure it truly aligns with Tailor's mission.

**Comment by adityatrivedi** [comment]
Thanks for the suggestion!  You're right that Tailor's primary mission is to analyze Swift source code.  Hence this feature is not on the roadmap.
