### ISSUE TITLE
Allow exceptions to lowerCamelCase rule in the case of all-caps acronyms

### ISSUE THREAD

**Issue by chadmoone** [sleekbyte/tailor#305]
For example, Apple's APIs typically expose a URL method argument as `URL`:
```swift 
init?(URL url: NSURL, resolvingAgainstBaseURL resolve: Bool)
convenience init(URL URL: NSURL)
init(URL URL: NSURL, entersReaderIfAvailable entersReaderIfAvailable: Bool)
init?(URL url: NSURL, statusCode statusCode: Int, HTTPVersion HTTPVersion: String?, headerFields headerFields: [String: String]?)
```
However, these methods would all be flagged by Tailor.

 What do you think about a rule which allows an exception to the lowerCamelCase rule in the case that the name begins with a range of 2 or more all-caps characters (to avoid letting UpperCamelCase pass), followed by camelCase after that?

**Comment by adityatrivedi** [comment]
This is a good idea!  It may lead to some false negatives, but since these methods are exposed by Apple's API, it is a worthwhile exception to permit.  We will add this functionality in a future release.

**Comment by ArtSabintsev** [comment]
The sooner the better :) I've added `// tailor : disable` to all those lines.

**Comment by adityatrivedi** [comment]
Release v0.5.0 is out!  It relaxes the `[lower-camel-case]` rule to allow for names that begin with acronyms.

**Comment by chadmoone** [comment]
👍 Excellent! Thanks for all your work on this project!
