### ISSUE TITLE
Use trailing closures for single closure args

### ISSUE THREAD

**Issue by a4sriniv** [sleekbyte/tailor#307]
**Preferred**
```swift
reversed = names.sort { s1, s2 in return s1 > s2 }
```

**Not Preferred**
```swift
reversed = names.sort({ s1, s2 in return s1 > s2 })
```

**Comment by andrew8712** [comment]
How about allowing this statement within the rule:

    reversedTopTen = names.sort({ s1, s2 in return s1 > s2 }).prefix(10)

?

**Comment by AntiMoron** [comment]
maybe this one is better ?
```swift
reversed = names.sort {$0 > $1 }
```

**Comment by andrew8712** [comment]
Huh? @AntiMoron how it's related to the topic? :)

**Comment by a4sriniv** [comment]
Hey @andrew8712, we think its best to keep this rule as it is, it will enforce this as the preferred style:

```swift
reversedTopTen = names.sort { s1, s2 in return s1 > s2 }.prefix(10)
firstName = names.sort { s1, s2 in return s1 > s2 }.first
```

**Comment by andrew8712** [comment]
But this style reduces readability, especially when the chain is long.
