### ISSUE TITLE
Grammar broken (line comments)

### ISSUE THREAD

**Issue by marcinwyszynski** [sleekbyte/tailor#315]
Using your version of ANTLR grammar for the file which looks like this:

```swift
class Person {
  var name: String

  init(name: String = "Marcin") {
    self.name = name
  }
} // class Person
```

...yields interesting results. Namely, the comment is being parsed as a class declaration and an invalid one at that. I would like to kindly suggest that you revert comment definitions to the [original](https://github.com/antlr/grammars-v4/blob/master/swift/Swift.g4).

**Comment by a4sriniv** [comment]
Thanks for pointing this out! The fix will be part of our next release :smile:

**Comment by marcinwyszynski** [comment]
![borat-dancing](https://cloud.githubusercontent.com/assets/571786/12722362/e8e172c2-c904-11e5-8e15-7b049bc67434.gif)
