### ISSUE TITLE
Extremely poor performance

### ISSUE THREAD

**Issue by marcinwyszynski** [sleekbyte/tailor#325]
I attempted to use Tailor to analyse [this open-source app](https://github.com/CatchChat/Yep). After 10 minutes of maxing out my 4 cores JVM OOMed. I assume this is a limitation based on ANTLR-generated parser being used but I was wondering if you can think of some ways of improving performance by at least an order of magnitude? ;) I'm afraid I don't have much experience to provide meaningful input but one thing that limited memory consumption (to some 1.2GB) when I played around with the grammar was something like this:

```
private static ParseTree parseTreeFrom(String content) {
  CharStream input = new UnbufferedCharStream(new StringReader(content));
  SwiftLexer lex = new SwiftLexer(input);
  lex.setTokenFactory(new CommonTokenFactory(true));
  TokenStream tokens = new UnbufferedTokenStream<CommonToken>(lex);
  SwiftParser parser = new SwiftParser(tokens);
  parser.setTrimParseTree(true);
  return parser.topLevel();
}
```

That did not curb insane CPU usage, though. I'm wondering if you have any insights.

**Comment by dlo** [comment]
Same. This project is incredibly cool, but the slowness has forced me to uninstall. Builds take 3-4x longer when using tailor. :cry:

**Comment by marcinwyszynski** [comment]
At [codebeat](https://codebeat.co) we've been working on Swift support for our static analysis platform and got inspired by your use of ANTLR. We took your version of the grammar, fixed and modified it heavily and... hit the wall in terms of performance. In my previous post I was really being a smartass, counting that you could do the job I should be doing - mostly because I'm totally incompetent in Java ;) But eventually I started digging into the matter and ended up improving performance by an order of magnitude to a point where using it in our project became borderline feasible. As a way of saying "thanks for inspiration" I'd like to share my findings.

First - the performance problem with large projects is caused by ANTLR's DFA cache causing problems with GC. Lexers and parsers for individual files are not getting garbage-collected because they're referred to by an ever-growing static cache object. This eventually leads to a situation where all the available memory is exhausted and the machine is spending most of it's time in GC cycles, each time reclaiming only a minimal amount of memory. The fix is to clear the cache either after every file (which we do) or every X files (which is possibly good for performance). Here's what we did - and please don't laugh at my Java foo ;)

```java
private static ParseTree parseTreeFrom(String content) {
  CharStream input = new UnbufferedCharStream(new StringReader(content));
  SwiftLexer lex = new SwiftLexer(input);
  lex.setTokenFactory(new CommonTokenFactory(true)); // conserve memory;
  TokenStream tokens = new UnbufferedTokenStream<CommonToken>(lex);
  SwiftParser parser = new SwiftParser(tokens);
  parser.setTrimParseTree(true); // conserve moar memory;
  parser.setErrorHandler(new BailErrorStrategy()); // never forgive;
  ParseTree ret = parser.topLevel();
  lex.getInterpreter().clearDFA();
  parser.getInterpreter().clearDFA();
  return ret;
}
```

So that brought memory usage under control and freed up cores which previously were busy doing GC. Now we could use those cores to process files in parallel so we used a threadpool with the size equal to the number of available cores. The obvious drawback of this approach is that you need to synchronise printing to the terminal but since parsing and analysis is what takes most of the CPU time synchronising output doesn't come with a significant performance penalty. But - your files will be printed in a non-deterministic order - in case you care.

Overall though ANTLR's performance has been a serious problem for us and we'll probably switch to using the handwritten LLVM-based parser by Apple. Let me know if you'd like to join forces on that!

**Comment by alykhank** [comment]
Thank you for the insights and recommendations @marcinwyszynski! We've been aware of these issues and have been attempting to incrementally improve the performance. In the previous release, we were able to cut runtime approximately in half by buffering output for multiple files and performing parsing/analysis in parallel. Now, our focus will be to improve memory consumption and CPU usage, with the recommendations you've provided. :smile: We'll investigate and respond with our findings!

**Comment by marcinwyszynski** [comment]
![maytheodds](https://cloud.githubusercontent.com/assets/571786/13202440/3dd1af7c-d89b-11e5-89b6-234fc64bcedb.jpg)
