### ISSUE TITLE
[lower-camel-case] Allow underscore prefix

### ISSUE THREAD

**Issue by charlieMonroe** [sleekbyte/tailor#329]
I personally prefer having all private method names and variables prefixed with underscore for one simple reason - when you come back to the code in a few months, you can easily spot which method/variable is privat/public.

Example:

`
private var _idleTimeInterval: CFTimeInterval = 0.0
`

This is detected as now `lower-camel-case`, while I believe it should be. I would like to keep tailor checking for lowerCamelCase in all other instances, but with the current behavior, I need to turn this option off.

Thanks! 

EDIT: This goes for `constant-naming` as well.

**Comment by adityatrivedi** [comment]
Based on our investigations, all Swift style guides suggest that this is a pattern from Objective-C that is no longer recommended in Swift.  Hence, we prefer to prevent prefixing variables and constants with an underscore in Tailor.

If you still wish to follow this naming convention, you may keep the rule(s) disabled or make this change in a separate fork.  The method that controls this is `isLowerCamelCaseOrAcronym()` in `CharFormatUtil.java`.
