### ISSUE TITLE
Except rules are ignored in .tailor.yml

### ISSUE THREAD

**Issue by lyptt** [sleekbyte/tailor#348]
Regardless of what I put in the except: block of the .tailor.yml file, none of these declarations are respected by tailor.

For example, with the following except block:

```
except:
    - trailing-whitespace
```

The trailing-whitespace rule is still being triggered.

**Comment by alykhank** [comment]
Thanks for reporting @lyptt.Which version of Tailor are you using? (e.g. `tailor -v`)

**Comment by lyptt** [comment]
I'm using tailor 0.5.0 as distributed with homebrew. Should I not be using homebrew to install tailor?

**Comment by alykhank** [comment]
You sure can! Just ensure to run `brew update && brew upgrade tailor` to get the latest version available :)

**Comment by lyptt** [comment]
Sure thing, looks like I'm on 0.6.0 now. Thanks for the help.
