### ISSUE TITLE
NoViableAltException when scanning AlamoFire

### ISSUE THREAD

**Issue by esheri3** [sleekbyte/tailor#361]
Scanning the https://github.com/Alamofire/Alamofire project produces numerous NoViableAltException ANTLR errors when using the Swift.g4 grammar file directly. Seeing this info will require setting the error handler and overriding reportError on the generated SwiftParser object:

ex: SwiftParser parser ...; parser.setErrorHandler(...);

Note that these errors do not appear visible when invoking tailor directly from the CLI. I'm assuming tailor is ignoring these errors, but this can impact completeness of the scan.

**Comment by alykhank** [comment]
That's correct, we purposely suppress the ANTLR parser errors (by overriding the error handler) and indicate that the file was skipped when running Tailor from the command-line.

We are regularly working to improve the correctness of our grammar by testing against popular open source Swift repositories and Apple's language reference. We are currently updating the grammar to support Swift 2.2.

**Comment by esheri3** [comment]
That's great news. Do you have a rough ETA you could share?
