### ISSUE TITLE
Granularity under UpperCamel

### ISSUE THREAD

**Issue by jeeftor** [sleekbyte/tailor#366]
I would love to have the ability to enforce naming conventions on only "some" things such as

classes
structs
functions
enums
etc.

Our specific use case is that we are still using c-style THIS_IS_AN_ENUM for our enums - and thus we get a lot errors we don't intent to fix

**Comment by alykhank** [comment]
Thanks for suggesting this! Its part of a larger feature we're hoping to introduce that will allow rule customization via the config file. We'll be tracking the feature in #382.
