### ISSUE TITLE
Support nested configuration

### ISSUE THREAD

**Issue by ElvisYang** [sleekbyte/tailor#390]
(It is a requirement) when I create a nested configuration, it should override some rules of configuration in root folder, just like https://github.com/realm/SwiftLint#nested-configurations in swiftlint

**Comment by adityatrivedi** [comment]
Hello @ElvisYang! As we prefer to keep the configuration options as simple as possible, this feature is not on our roadmap at the current time.

**Comment by ElvisYang** [comment]
got it, Thanks @adityatrivedi
