### ISSUE TITLE
tailor run script is not showing issues in Xcode

### ISSUE THREAD

**Issue by SavitaJuyal** [sleekbyte/tailor#399]
**Tailor Version:** v0.9.0

**Swift Version:** 2.2

**Platform (Mac/Linux/Windows/CI):** Mac

**Installation Method:** Homebrew

### Steps to Reproduce Issue

1. I used homebrew to install tailor : brew install tailor
2. Added run script in terminal through this comand : tailor --xcode path

Tailor have been successfully installed, I have checked this.

### Expected Behavior
It should show error on running code in Xcode.

### Actual Behavior
Stuck in code while running script, nothings shows and sometimes fails with exception.

Please check and respond asap

**Comment by alykhank** [comment]
@SavitaJuyal would you be able to join us on [Gitter](https://gitter.im/sleekbyte/tailor) so we can discuss and investigate the issue further?

**Comment by alykhank** [comment]
@SavitaJuyal Tailor 0.9.1 has several performance improvements. Please update and indicate if this behaviour persists.

**Comment by alykhank** [comment]
Followed up via [Gitter](https://gitter.im/sleekbyte/tailor).
