### ISSUE TITLE
[parenthesis-whitespace] rule flags parens preceded by braces

### ISSUE THREAD

**Issue by ArtSabintsev** [sleekbyte/tailor#400]
**Tailor Version:** v0.9.0
**Swift Version:** 2.2
**Platform (Mac/Linux/Windows/CI):** Mac
**Installation Method:** Homebrew

The Parenthesis-Whitespace rule should not exist. It makes no sense, especially in closures.

It turns functions that look like this:

```
MyClass.executeClosure { (param) -> retVal in
                   
}
```

to the following:

```
MyClass.executeClosure {(param) -> retVal in
                   
}
```

Looks really ugly. 

I'm disabling the rule, but I hope you consider removing it.

**Comment by alykhank** [comment]
How about cases like these?

*Preferred*

```swift
func sum(a: Int, b: Int) -> Int {
  return a + b;
}

print("Hello, World!")
```

*Not Preferred*

```swift

func sum ( a: Int, b: Int ) -> Int {
  return a + b;
}

print( "Hello, World!" )
```

**Comment by ArtSabintsev** [comment]
Then make the rule more stringent, so it doesn't flag situations where a `{` precedes the parenthesis.

**Comment by ramadey** [comment]
I agree with @ArtSabintsev that Tailor should not flag instances of `(` succeeding `{`.  However, I also believe that @ArtSabintsev could have been a bit more friendly with his request.  I am of the understanding that the maintainers of this project work on Tailor in their leisure time.  They have released Tailor for the benefit of the Swift developer community and we should appreciate them taking some time out of their busy schedule for creating and maintaining the tool.

**Comment by ArtSabintsev** [comment]
My apologies - I didn't mean to be harsh if I came of that way. I, too, am an OSS developer, so I know how much time it takes to main this stuff.

Again, my apologies if I came off sounding rude - not my intention at all. Same goes for my comments in #401.
