### ISSUE TITLE
Incorrect Rule: [brace-style] when `throws` 

### ISSUE THREAD

**Issue by brendanjerwin** [sleekbyte/tailor#405]
**Tailor Version:** v0.9.0

**Swift Version:** 2.2

**Platform (Mac/Linux/Windows/CI):** Mac

**Installation Method:** Homebrew

### Steps to Reproduce Issue

This is what is causing it now. I think its just the `throws` though.

1. `public convenience init(name: String...) throws {`

### Expected Behavior
 No error

### Actual Behavior
`[brace-style] Opening brace should have exactly one space before it`

**Comment by objectmethod** [comment]
+1
