### ISSUE TITLE
func ~=<T where T: Hashable> fails angle-bracket-whitespace rule

### ISSUE THREAD

**Issue by courteouselk** [sleekbyte/tailor#420]
**Tailor Version:** v0.9.0
**Swift Version:** 2.2.1
**Platform (Mac/Linux/Windows/CI):** Mac
**Installation Method:** codeclimate.com

### Steps to Reproduce Issue

1. Declare operator:

    ````swift
    func ~=<T where T: Hashable>(pattern: Set<T>, value: T) -> Bool {
        return pattern.contains(value)
    }
    ````

2. Run the check

### Expected Behavior

`angle-bracket-whitespace` should not fail

### Actual Behavior

`angle-bracket-whitespace` fails

**Comment by a4sriniv** [comment]
Hey @courteouselk, sorry for the late response! The `angle-bracket-whitespace` rule actually makes an exception for operator definitions, it requires a single space to be present between the operator and the opening angle bracket. It's easy to confuse the angle bracket as part of the operator being defined, so we added in an exception  just for this case. I realize the documentation for the rule doesn't reflect this, so I'll update that.
