### ISSUE TITLE
Limiting CPU load

### ISSUE THREAD

**Issue by jgonera** [sleekbyte/tailor#426]
**Tailor Version:** v0.1.0

**Swift Version:** 2.2

**Platform (Mac/Linux/Windows/CI):** Linux

**Installation Method:** CodeClimate

Is there a way to tell Tailor to not use up all the available CPU time? We use it as a part of our CodeClimate setup and two Tailor processes can exhaust a 16-core CPU. Is there a way to limit the number of threads it creates?

**Comment by adityatrivedi** [comment]
Sorry for the lack of response in the past months, our team has been pretty time constrained 😟 Unfortunately we don’t believe this can be configured from the standard Code Climate setup, but if this is still an issue you could attempt to modify the [Code Climate container](https://github.com/codeclimate/codeclimate/blob/master/lib/cc/analyzer/container.rb) code to configure Docker resource limits and then install your custom fork of Code Climate.
