### ISSUE TITLE
Multiple conditionals should be valid

### ISSUE THREAD

**Issue by thefredelement** [sleekbyte/tailor#427]
**Tailor Version:** v0.1.0

**Swift Version:** 2.2

**Platform (Mac/Linux/Windows/CI):** Mac

**Installation Method:** curl script

### Steps to Reproduce Issue
```swift
guard
   let strongSelf = self,
   let data = jsonData,
   let convos = data["items"] as? [[String: AnyObject]] else {

      return
   }
```
### Expected Behavior

Should be valid

### Actual Behavior

Generates a violation

**Comment by a4sriniv** [comment]
Hi @thefredelement! Tailor does allow the use of multiple conditionals. In this scenario, the violations are generated to point out that the `let` (s) before `data` and `convos` are redundant.

**Comment by thefredelement** [comment]
Hi @a4sriniv - thanks for replying, the lets aren't redundant because of the type cast of [[String: AnyObject]]. It could thrown into one ugly line though if that's what you mean?

**Comment by a4sriniv** [comment]
I think something like this should work:

```swift
guard 
    let strongSelf = self,
        data = jsonData,
        convos = data["items"] as? [[String: AnyObject]] 
    else {
        return
    }
```

**Comment by thefredelement** [comment]
Ah, beautiful :) I had no idea.. 👍
