### ISSUE TITLE
How do I distinguish between a function call and constructor invocation (question)

### ISSUE THREAD

**Issue by venkatgyambavantha** [sleekbyte/tailor#439]
**Tailor Version:** v0.10.0

**Swift Version:** 2.2

**Platform (Mac/Linux/Windows/CI):** Mac

**Installation Method:** Homebrew

**Comment by adityatrivedi** [comment]
Can you please provide some context?

**Comment by venkatgyambavantha** [comment]
If I have two classes say A & B

class A {
 public init() {
       }
}
In class B, I declare a variable something like var testVar = A(); How do I figure out that it is a constructor call. Right now, I get a callback in enterFunctionCallExpression

**Comment by clayreimann** [comment]
From what I can see, there is nothing in the grammar that would let you know that. The kind of tool that you want to build would likely require cross-file analysis and from what I can see in `Tailor.java` all of the listeners are run on each file independently, so I don't think that the rule you're looking to build can exist in Tailor as it currently exists.
