### ISSUE TITLE
Add length rules to .tailor.yml

### ISSUE THREAD

**Issue by pablog** [sleekbyte/tailor#449]
I couldn't find a way to add the length rules to `.taylor.yml` file.

I mean, if in my `.taylor.yml` file I have:

```
only:
  - max-file-length
```

It takes this rule into account, but I couldn't specify via `.tailor.yml` file how many lines I want to allow. Of course I'm having the same issue with every length rule.

**Comment by adityatrivedi** [comment]
@pablog, Tailor as of right now does allow you to specify any length rules to the `.tailor.yml` file.  This is something we intend to start work on shortly. You can follow the progress on #382.
