### ISSUE TITLE
Support Swift 3

### ISSUE THREAD

**Issue by esheri3** [sleekbyte/tailor#450]
What is the gameplan / status regarding supporting the recently released Swift 3 update? This release appears to introduce syntax changes that would affect the underlying parser. Is this under consideration?

**Comment by adityatrivedi** [comment]
Hey @esheri3! We released [Tailor 0.11.0](https://github.com/sleekbyte/tailor/releases/tag/v0.11.0) more than a week ago with compatibility for Swift 3.  Please ensure that you are using version 0.11.0 and let us know of any problems.

**Comment by esheri3** [comment]
Yikes - sorry I missed it. Is this backwards compatible with Swift 2.2 as well? Thank you for all the hard work.

**Comment by adityatrivedi** [comment]
No worries! Sadly, version 0.11.0 is not backwards compatible.

**Comment by EvgenyKarkan** [comment]
Hey @adityatrivedi - how can I install specific Tailor version?
I want 0.11.0 version with Swift 2 support

**Comment by adityatrivedi** [comment]
Hi @EvgenyKarkan! Version 0.11.0 only supports Swift 3.0.  To get Swift 2 support, you will need to use older versions of Tailor by either
1. manually installing a specific version of Tailor from the [release](https://github.com/sleekbyte/tailor/releases) page or,
2. running the [install script](https://github.com/sleekbyte/tailor/blob/gh-pages/install.sh) after replacing `TAILOR_VERSION` with an appropriate version (eg. `0.10.1`).

**Comment by EvgenyKarkan** [comment]
OK, thank you.
