### ISSUE TITLE
Can't parse new access levels (open and fileprivate)

### ISSUE THREAD

**Issue by dbmrq** [sleekbyte/tailor#452]
**Tailor Version:** v0.11.0

**Swift Version:** 3.0

**Platform (Mac/Linux/Windows/CI):** Mac

**Installation Method:** Homebrew

### Steps to Reproduce Issue

Paste this at the command line:

```bash
cat <<EOF > whatever.swift
class Whatever: Object {
    open func something() {}
    fileprivate func somethingElse() {}
}
EOF
tailor whatever.swift
```

### Expected Behavior

It should work (remove `open` and `fileprivate` and it does).

### Actual Behavior

It doesn't work.

**Comment by adityatrivedi** [comment]
@dbmrq thank you for reporting the bug.  We will attempt to get this fixed and integrated into the next release as soon as possible.
