### ISSUE TITLE
Remove upper-camel-case for enumerations

### ISSUE THREAD

**Issue by dbmrq** [sleekbyte/tailor#453]
**Tailor Version:** v0.11.0

**Swift Version:** 3.0

**Platform (Mac/Linux/Windows/CI):** Mac

**Installation Method:** Homebrew

### Expected Behavior

[In Swift 3, enum cases should be in lower camel case](https://www.google.com.br/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwis47-jgsjPAhXKDZAKHfatBn8QygQIJDAA&url=https%3A%2F%2Fdeveloper.apple.com%2Flibrary%2Fcontent%2Fdocumentation%2FSwift%2FConceptual%2FSwift_Programming_Language%2FEnumerations.html%23%2F%2Fapple_ref%2Fdoc%2Fuid%2FTP40014097-CH12-ID146&usg=AFQjCNGV7uwVrfjc8l41yyPXSnMR774Q1w&sig2=S4OblNMH6W6STTgEsgqNeg)

### Actual Behavior

The `upper-camel-case` rule applies to enums.

**Comment by adityatrivedi** [comment]
Thank you for reporting the update in [The Swift Programming Language](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/) @dbmrq.  We will get this addressed very soon in the next release.
