### ISSUE TITLE
Running tailor in a run script phase in Xcode

### ISSUE THREAD

**Issue by Anders123fr** [sleekbyte/tailor#464]
Right now the README only contains information on how to add tailor to a run script phase in your Xcode project target, but then it will run every time i compile my app, which will make it very slow to compile when I am developing.
I know that it is possible to run `tailor` in the command line, but I really like that it shows the warnings inside Xcode.
So is it possible to make a new scheme where you can run the `tailor` command, and then have another scheme for development? Or is it possible to check directly in the run script, wether `tailor` should be executed, depending on if we are building or analyzing the target

**Comment by adityatrivedi** [comment]
Thank you for getting in touch @Anders123fr.  One way to get around this is to run Tailor whenever you choose the analyze the project natively (⇧⌘B).  This can be done by: 

1. Adding a new configuration, say `Analyze`,  to the project
<img width="1020" alt="screen shot 2016-11-30 at 12 29 34 am" src="https://cloud.githubusercontent.com/assets/1791760/20745188/fba98222-b694-11e6-8212-038333b259b3.png">

2. Modifying the active scheme's `Analyze` phase to use the new build configuration created above
<img width="899" alt="screen shot 2016-11-30 at 12 37 08 am" src="https://cloud.githubusercontent.com/assets/1791760/20745259/57e71acc-b695-11e6-9671-092f89029467.png">

3. Tweaking the build phase run script to run Tailor **only** when analyzing the project (⇧⌘B)
```bash
if [ "${CONFIGURATION}" = "Analyze" ]; then
    if hash tailor 2>/dev/null; then
        tailor
    else
        echo "warning: Please install Tailor from https://tailor.sh"
    fi
fi
```

Another solution to this problem would be to add Tailor as a Xcode extension.  Let me know if this helps :)

**Comment by Anders123fr** [comment]
Hi @adityatrivedi,

Thank you very much for your explanation!
It was exactly what I was looking for. 
Now it runs the tailor script only when i do an `Analyze`. 

And yeah would be good to show this explanation somewhere in the `README`, or even better as an Xcode extension,  as I am probably not the only one who didn't figure this out. 

It's a really great tool, I must say!

**Comment by adityatrivedi** [comment]
@Anders123fr thank you for using Tailor :)  I shall update the README for now and create a work item for the Xcode extension.
