### ISSUE TITLE
Configure Xcode to Analyze Code Natively way does not work for workspaces

### ISSUE THREAD

**Issue by evgzor** [sleekbyte/tailor#470]
**Tailor Version:** v0.11.1

**Swift Version:** 3.0

**Platform (Mac/Linux/Windows/CI):** Mac OS Siera

**Installation Method:** Curl

### Steps to Reproduce Issue

1. Use Xcode as described https://github.com/sleekbyte/tailor "Configure Xcode to Analyze Code Natively" try to analyze workspace (create Analyze scheme and run Analyze from Xcode menu) for example 

### Expected Behavior
Analyze workspace
### Actual Behavior
Cannot find pods

**Comment by adityatrivedi** [comment]
@evgzor, what pods is it looking for?  Tailor doesn't use any pods.

**Comment by evgzor** [comment]
The issue is about how to analyzing workspaces as described in your documentation. It works for the project but does not work for the workspaces. Instead of pods could be another project. Did u try analyze workspace?

**Comment by edasque** [comment]
I have the same issue. As a result, instead of analyzing 4 files quickly, it analyses 59  (the pods my project is using).

**Comment by adityatrivedi** [comment]
@evgzor, the **only** way I can get select projects to run Tailor natively in a workspace is by following the steps in the [README](https://github.com/sleekbyte/tailor#automatic-xcode-integration) for each project in the workspace you wish to analyze.  After configuring those projects, you will have to edit the running scheme's build rule to build the targets of the projects you want to analyze.

In the following example, I have a workspace, `DemoWorkspace`, with two Swift projects namely, `DemoProject1` and `DemoProject2`.  Both the projects have the aforementioned `Analyze` configuration and `build phase run script`.  The `Build` rule in the scheme for `DemoProject1` has been edited to also build the target for `DemoProject2`.  Pressing ⇧⌘B will now analyze both `DemoProject1` and `DemoProject2` as shown in the second screenshot.  Let me know if that works for you.

<img width="1280" alt="screen shot 2017-01-20 at 11 28 01 pm" src="https://cloud.githubusercontent.com/assets/1791760/22172915/1f058ddc-df68-11e6-888d-abb1a4a97658.png">

<img width="278" alt="screen shot 2017-01-20 at 11 30 00 pm" src="https://cloud.githubusercontent.com/assets/1791760/22172925/6a957686-df68-11e6-996d-f47d3bbf2d20.png">

**Comment by adityatrivedi** [comment]
@edasque, would you be abe to share your workspace structure?  You can direct Tailor to ignore analysis for certain directories by [defining](https://github.com/sleekbyte/tailor#configuration) the following `.tailor.yml` configuration file in the root of the project:

```yaml
exclude:
  - pods
```

**Comment by evgzor** [comment]
@adityatrivedi I knew about that possibility to run scripts in each project but it's a bit awkward. I just wanted to have the possibility to check workspace by only one command referenced to the workspace, not for each project. For instance, I had 20 separated projects and it would be not so convenient to write the build script for each of them. It's really enhancement...

**Comment by adityatrivedi** [comment]
@evgzor, sadly this appears to be a limitation with Xcode itself.  Maybe you could file a [radar](https://developer.apple.com/bugreporter/) regarding this against Xcode and label it as an **enhancement**.
