### ISSUE TITLE
Style Guides

### ISSUE THREAD

**Issue by nikitaame** [sleekbyte/tailor#472]
Is there a way to adhere to a particular style guide? Such as Ray Wenderlich's instead of Github's

**Comment by adityatrivedi** [comment]
Hi @nikitaame, there is no way to adhere to a particular style guide.  When we started designing `tailor`, we wanted to enforce the common style guidelines outlined in [The Swift Programming Language][], [GitHub][], [Ray Wenderlich][], and [Coursera][] style guides.

[The Swift Programming Language]: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/
[GitHub]: https://github.com/github/swift-style-guide
[Ray Wenderlich]: https://github.com/raywenderlich/swift-style-guide
[Coursera]: https://github.com/coursera/swift-style-guide
