### ISSUE TITLE
Incorrect handling of escaped identifiers

### ISSUE THREAD

**Issue by wheerd** [sleekbyte/tailor#474]
**Tailor Version:** v0.11.1

**Swift Version:** 3.0.2

**Platform:** Windows

**Installation Method:** Install Script

### Example file

Running tailor with default settings on this example file finds a violation where it should not:

```swift
class SomeClass {
    let `fubar`: Int
    let fubar2: Int
}
```

The second property is there to verify that the issue arises from the backticks.

### Expected Behavior

No violation

### Actual Behavior

```
Analyzing 1 file:
.

********** example.swift **********
example.swift:2:9: warning: [constant-naming] Global Constant should be either lowerCamelCase or UpperCamelCase

Analyzed 1 file, skipped 0 files, and detected 1 violation (0 errors, 1 warning).
```

**Comment by adityatrivedi** [comment]
Closing this issue and tracking it under #460.
