### ISSUE TITLE
Enforce whitespace checks

### ISSUE THREAD

**Issue by nehasingh2293** [sleekbyte/tailor#89]
- [x] one blank line between methods
- [x] whitespace around operators when defining them

**Preferred**

``` swift
prefix operator += {}
```

**Not Preferred**

``` swift
prefix operator   +-+ {}
prefix operator **    {}
```
- [x] only one space between opening construct and `{` brace (except for compound assignment operators `+=`)

**Preferred**

``` swift
func helloWorld {
 // do something
}
```

**Not Preferred**

``` swift
func helloWorld{
    // do something
}

class hello     {
    var message: String
}
```
- [x] one space after `//` in comments

**Preferred**

``` swift
// this is a comment
```

**Not Preferred**

``` swift
//this is a comment
```
- [x] start and end multi-line comments with a single space

**Preferred**

``` swift
/* This is a
multiline comment */
```

**Not Preferred**

``` swift
/*This is a
multiline comment*/
```
- [x] Colon directly after identifier, then space and type name

**Preferred**

``` swift
var x: Int = 2
```

**Not Preferred**

``` swift
var x : Int
var y:   String
```
- [x] Colon directly after key type, then space and value for dictionary types

**Preferred**

``` swift
var x = [ 'key1': 1, 'key2': 2 ]
var y: [ Int: String ]
```

**Not Preferred**

``` swift
var x = [ 'key1' : 1, 'key2':  3]
var y: [ Int :    String ]
```
- [x] Colon directly after case label, then space and statements

**Preferred**

``` swift
switch character {
case "a": doSomething(a);
default: alert();
}
```

**Not Preferred**

``` swift
switch character {
case "a" : doSomething(a);
default:     alert();
}
```
- [x] Colon directly after class/struct/protocol/extension name, followed by space, followed by type inheritance list

**Preferred**

``` swift
class ClassName: BaseClass {
}

struct StructName: BaseStruct {
}

protocol ProtocolName: AnotherProtocol {
}

extension TypeName: ProtocolName {
}
```

**Not Preferred**

``` swift
class ClassName : BaseClass {
}

struct StructName:  BaseStruct {
}

protocol ProtocolName:AnotherProtocol {
}

extension TypeName : ProtocolName {
}
```
- [x] Single space before and after colon in a conditional expression

**Preferred**

``` swift
var x = condition ? a : b
```

**Not Preferred**

``` swift
var x = condition ? a: b
var x = condition ? a   : b
```
- [x] Tuple name, followed by colon, followed by a space, followed by value

**Preferred**

``` swift
var y = (key: 1, value: 2)
```

**Not Preferred**

``` swift
var y = (key:1, value : 2)
```
- [x] Colon directly after typeName, followed by a space in generic parameter clauses

**Preferred**

``` swift
func someFunction<T: SomeClass, U: SomeProtocol>(someT: T, someU: U) {
}
```

**Not Preferred** 

``` swift
func someFunction<T : SomeClass, U:SomeProtocol>(someT: T, someU: U) {
}
```
- [x] Check for a space before and after '->' in function and closure declarations
- [x] Check for a space before and after '->' in subscripts
- [x] Check for a space before and after '->' in function types

**Comment by git-commit** [comment]
Could you change the rule for [function-whitespace] to not apply when at the top of a class or the very bottom?

See this screenshot for an example of a in my opinion wrong linting:
![screen shot 2016-05-18 at 22 18 22](https://cloud.githubusercontent.com/assets/3263955/15373549/8261fe18-1d46-11e6-8900-67571d888d8b.png)
